food_item = str(input('Enter food item name:\n'))
item_price = float(input('Enter item price:\n'))
item_quantity = int(input('Enter item quantity:\n'))
print()
print('RECEIPT')
print(item_quantity,food_item,'@','$',item_price,'=',item_quantity*item_price)
print('Total cost: $',item_price*item_quantity)
print()
print()
food_item2 = input('Enter second food item name:\n')
item_price2 = float(input('Enter item price:\n'))
item_quantity2 = float(input('Enter item quantity:\n'))
print()
print('RECEIPT')
total_cost = (item_price*item_quantity)+(item_price2*item_quantity2)
print(item_quantity,food_item,'@','$',item_price,'=',item_quantity*item_price)
print(item_quantity2,food_item2,'@','$',item_price2,'=',item_quantity2*item_price2)
print('Total cost: $',total_cost)
print()
print('15% gratuity: $ ', 0.15*total_cost)
print(total_cost+(0.15*total_cost))